name: DropChestNH
version: 1.02
author: Morthis
description: Chests can be configured to pick items up off the ground, or add/remove items from passing storage minecarts.
main: com.noheroes.dropchestnh.DropChestNH
commands:
  dropchest:
    description: Dropchest commands
    aliases: [dc] 
    usage: "Alias: '/dc'. Type '/dropchest help' for more information."
permissions:
  dropchest.create.suck:
    description: Allows user to create suck filters
    default: op
  dropchest.create.pull:
    description: Allows user to create pull filters
    default: op
  dropchest.create.push:
    description: Allows user to create push filters
    default: op
  dropchest.admin.basic:
    description: Gives user access to basic admin commands (information about other chests only)
    default: op
  dropchest.admin.full:
    description: Gives full admin access (editing/removing any chest)
    default: op
  dropchest.create.*:
    description: Gives access to all filters
    children:
        dropchest.create.suck: true
        dropchest.create.pull: true
        dropchest.create.push: true