name: DropChest
version: 0.1
author: Morthis
description: Chests can be configured to pick items up off the ground, or add/remove items from passing storage minecarts.
main: com.noheroes.dropchest.DropChest
commands:
  dropchest:
    description: Dropchest commands
    aliases: [dc] 
    usage: "Alias: '/dc'. Type '/dropchest help' for more information."